name: Setup Ubuntu with Composer and PHP 8
on:
  push:
    tags:
      - '*'

jobs:
  setup-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Updating Dependencies + zip
        run: |
          cd ~
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          HASH=`curl -sS https://composer.github.io/installer.sig`
          sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

          sudo update-alternatives --set php /usr/bin/php8.0

          php -v